name: pull-request-review
description: Review pull requests with AI (LLM)
author: remarkablemark

inputs:
  model:
    description: Language model name
    default: codellama
    required: false
  prompt:
    description: Input prompt before the PR diff
    default: 'Code review the diff:'
    required: false
  comment-header:
    description: Comment title in Markdown
    default: '# Pull Request Review'
    required: false
  token:
    description: GitHub token
    default: ${{ github.token }}
    required: false

runs:
  using: composite
  steps:
    - name: Setup ollama
      uses: ai-action/setup-ollama@v1

    - name: Checkout repository
      uses: actions/checkout@v6

    - name: Comment code review
      shell: bash
      run: |
        PROMPT=$(printf '%s\n%s' "$PROMPT" "$(gh pr diff $PR_NUMBER)")
        CODE_REVIEW=$(ollama run $MODEL "$PROMPT")
        COMMENT=$(printf '%s\n\n%s' "$COMMENT" "$CODE_REVIEW")
        gh pr comment $PR_NUMBER --body "$COMMENT"
      env:
        COMMENT: ${{ inputs.comment-header }}
        GH_TOKEN: ${{ inputs.token }}
        MODEL: ${{ inputs.model }}
        PR_NUMBER: ${{ github.event.pull_request.number }}
        PROMPT: ${{ inputs.prompt }}

branding:
  icon: code
  color: gray-dark
