name: pull-request-review
description: Review pull request code with AI
author: remarkablemark
inputs:
  version:
    description: Description
    required: false
    default: 1.2.3
runs:
  using: composite
  steps:
    - name: Print version
      shell: bash
      run: |
        echo 'version: ${{ inputs.version }}'
branding:
  icon: activity
  color: white
